POST http://localhost:3050/api/v1/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyMzRAbWFpbC5jb20iLCJleHAiOjE3Mjg0Mjc1NTYsInVzZXJJZCI6MX0.mMRQxjGfGRSiMYBwzB8Z2JpvTrrd6c8fpZGSCO8Ogpo

{
    "title": "First event",
    "description": "Test event description",
    "date": "2025-01-01T15:30:00.000Z",
    "location": "This is a test location"
}